apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cosmic-flight-sim

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: cosmic-flight-simulator
  managed-by: kustomize
