apiVersion: v1
kind: Service
metadata:
  name: cosmic-flight-simulator-service
  namespace: cosmic-flight-sim
  labels:
    app: cosmic-flight-simulator
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: cosmic-flight-simulator
